global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'default'

  routes:
    - match:
        severity: critical
      receiver: 'slack-critical'
      group_wait: 10s

    - match:
        severity: warning
      receiver: 'telegram-warning'
      group_wait: 30s

receivers:
  - name: 'default'
    email_configs:
      - to: 'your-email@example.com'
        from: 'alertmanager@example.com'
        smarthost: 'smtp.example.com:587'
        auth_username: 'your-email@example.com'
        auth_password: 'your-email-password'

  - name: 'slack-critical'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/your/slack/webhook'
        channel: '#critical-alerts'
        send_resolved: true

  - name: 'telegram-warning'
    telegram_configs:
      - api_url: 'https://api.telegram.org/bot<your-telegram-bot-token>/sendMessage'
        chat_id: '<your-telegram-chat-id>'
        message: '{{ template "telegram.default.message" . }}'
        send_resolved: true

templates:
  - '/etc/alertmanager/*.tmpl'
