#!/bin/bash 
set -e

mkdir -p certs

openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
-keyout certs/selfsigned.key \
-out certs/selfsigned.crt \
-subj "/C=RU/ST=SPB/L=SPB/O=MyOrg/OU=MyDep/CN=nginx.selfhosted" \
-addext "subjectAltName=DNS:nginx,DNS:localhost"